# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

helloPG <- function(n, z) {
    .Call('rpg3_helloPG', PACKAGE = 'rpg3', n, z)
}

rpg3 <- function(n, z) {
    .Call('rpg3_rpg3', PACKAGE = 'rpg3', n, z)
}
